/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as PocArabicPdfRouteImport } from './routes/poc-arabic-pdf'
import { Route as PocArabicImageRouteImport } from './routes/poc-arabic-image'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPostPreviewsRouteImport } from './routes/_authenticated/post-previews'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedCampaignsCampaignIdRouteImport } from './routes/_authenticated/campaigns.$campaignId'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const PocArabicPdfRoute = PocArabicPdfRouteImport.update({
  id: '/poc-arabic-pdf',
  path: '/poc-arabic-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PocArabicImageRoute = PocArabicImageRouteImport.update({
  id: '/poc-arabic-image',
  path: '/poc-arabic-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostPreviewsRoute =
  AuthenticatedPostPreviewsRouteImport.update({
    id: '/post-previews',
    path: '/post-previews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsCampaignIdRoute =
  AuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/index': typeof Char91indexChar93Route
  '/poc-arabic-image': typeof PocArabicImageRoute
  '/poc-arabic-pdf': typeof PocArabicPdfRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/post-previews': typeof AuthenticatedPostPreviewsRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/index': typeof Char91indexChar93Route
  '/poc-arabic-image': typeof PocArabicImageRoute
  '/poc-arabic-pdf': typeof PocArabicPdfRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/post-previews': typeof AuthenticatedPostPreviewsRoute
  '/': typeof AuthenticatedIndexRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/index': typeof Char91indexChar93Route
  '/poc-arabic-image': typeof PocArabicImageRoute
  '/poc-arabic-pdf': typeof PocArabicPdfRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/post-previews': typeof AuthenticatedPostPreviewsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/index'
    | '/poc-arabic-image'
    | '/poc-arabic-pdf'
    | '/admin'
    | '/post-previews'
    | '/campaigns/$campaignId'
    | '/projects/$id'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/index'
    | '/poc-arabic-image'
    | '/poc-arabic-pdf'
    | '/admin'
    | '/post-previews'
    | '/'
    | '/campaigns/$campaignId'
    | '/projects/$id'
    | '/campaigns'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/index'
    | '/poc-arabic-image'
    | '/poc-arabic-pdf'
    | '/_authenticated/admin'
    | '/_authenticated/post-previews'
    | '/_authenticated/'
    | '/_authenticated/campaigns/$campaignId'
    | '/_authenticated/projects/$id'
    | '/_authenticated/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  PocArabicImageRoute: typeof PocArabicImageRoute
  PocArabicPdfRoute: typeof PocArabicPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc-arabic-pdf': {
      id: '/poc-arabic-pdf'
      path: '/poc-arabic-pdf'
      fullPath: '/poc-arabic-pdf'
      preLoaderRoute: typeof PocArabicPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc-arabic-image': {
      id: '/poc-arabic-image'
      path: '/poc-arabic-image'
      fullPath: '/poc-arabic-image'
      preLoaderRoute: typeof PocArabicImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-previews': {
      id: '/_authenticated/post-previews'
      path: '/post-previews'
      fullPath: '/post-previews'
      preLoaderRoute: typeof AuthenticatedPostPreviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$campaignId': {
      id: '/_authenticated/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPostPreviewsRoute: typeof AuthenticatedPostPreviewsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCampaignsCampaignIdRoute: typeof AuthenticatedCampaignsCampaignIdRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPostPreviewsRoute: AuthenticatedPostPreviewsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCampaignsCampaignIdRoute: AuthenticatedCampaignsCampaignIdRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  PocArabicImageRoute: PocArabicImageRoute,
  PocArabicPdfRoute: PocArabicPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
